services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 8000:8000
    volumes:
      - ./server:/app

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - ignore:/app/node_modules

volumes:
  ignore:
