services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    env_file:
      - path: ./server.env
        required: false
      - ./server/.env.example
    ports:
      - 5432:5432
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./server.env
        required: false
      - ./server/.env.example
    ports:
      - 8000:8000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/server:/app
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./client.env
        required: false
      - ./client/.env.example
    ports:
      - 3000:3000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/client:/app
      - ignore:/app/node_modules

volumes:
  ignore:
