# Generated by Django 5.2.8 on 2025-12-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_feeding_remove_booking_room"),
        ("zoo", "0002_building_room_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="room",
            name="building",
        ),
        migrations.CreateModel(
            name="Enclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "habitat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zoo.habitat"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Building",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
