# Generated by Django 5.2.8 on 2025-12-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_feeding_remove_booking_room"),
        ("zoo", "0003_habitat_remove_room_building_enclosure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="enclosure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zoo.enclosure"
            ),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
